### PR TITLE
Multithread

### PR DESCRIPTION
**Pull request by hkgumbs**
@trptcolin @robertjlooby 
This PR is based on #1 and passes SimultaneousTestSuite.TimeToComplete

### CODE REVIEW

**Comment by hkgumbs** [comment]
I relied heavily on the acceptance tests to arrive at this solution. I couldn't think of a way to test it without spinning up a multithreaded server. Is there some way I could have done it so that it were more test-driven?

**Comment by trptcolin** [comment]
Due to the new commit / force-push to PR #1, this PR now looks like it has a bunch of extra commits on it - can you rebase master into this & the other PRs to make them easier to review & make the merges cleaner?

Reviewing [that one commit that's about this feature](https://github.com/hkgumbs/webserver-clojure/commit/1aac1e12dd6c9587f862ef797b9a9e80921ea171), I definitely think you can write unit tests here for at least the dispatch function, without having anything to do w/ concurrency. To do so, you'd need to inject a fake socket, one that sets up the right input and lets you track what output was sent to it. That probably means using `clojure.core/proxy` to create an instance of a subclass of `java.net.Socket`, and using your own input/output streams and whatever other feature you need to in order to avoid having it try & use real network communication. You can also refer to [the fake socket in FitNesse's implementation](https://github.com/unclebob/fitnesse/blob/51642419a8441428df7db00c00fe6eb1dc2df173/src/fitnesse/util/MockSocket.java) for an example of this kind of thing.

I'm also surprised that the multithreading test passes with just a `newSingleThreadExecutor` - only 1 thread is working on requests, and one (the main thread) on accepting them! I wonder what memory usage is like, since [the javadoc for newSingleThreadExecutor](http://docs.oracle.com/javase/7/docs/api/java/util/concurrent/Executors.html#newSingleThreadExecutor()) says it uses an unbounded queue. I suspect if the server were exposed to a lot more load, it might run out of memory and crash instead of dropping requests - that would be an interesting thing to test out & see.

**Comment by hkgumbs** [comment]
@trptcolin Re: the ```newSingleThreadExecutor```, I believe that acceptance test is platform-specific. Another apprentice said that they needed 8 threads to get that test running, but my machine is much newer. In any case, wouldn't testing with many more connections than cob_spec asks for and/or my tic-tac-toe game requires violate the principle "What is the simplest thing that could possibly work?"

**Comment by hkgumbs** [comment]
@trptcolin Re: testing dispatch
In my latest commit, I covered one branch of that function with the test that used to cover respond-400. I don't see how testing the other branch, ```app/handle``` makes any sense though because it would make the test dependent on the app by which the server is backed. That test would break as soon as I switch out cob-app for tic-tac-toe, and I can't think of a test that would be blind to the innards of cob_spec's behavior.

**Comment by trptcolin** [comment]
RE: testing all branches of the app - it sounds like you want to remove the dependency on cob_app. That sounds like a good idea. But currently, this `webserver.core` namespace does a few things:

1. Wiring up dependencies.
2. Logic about accepting sockets, dispatching
3. Reading/parsing headers

I'd imagine it would make testing your http server logic much easier if those concerns were separated, and the `-main` entry point was in a namespace that was *only* responsible for wiring together cob_app and the web server, injecting dependencies where needed.

`core`, incidentally, is a common name in Clojure-land, but it's problematic because it means "center of the app, upon which everything depends" and also "the highest-level entry point of the system", depending on what you look at.

**Comment by hkgumbs** [comment]
@trptcolin I see what you mean. Can I do those changes on a different PR, so that I can merge the other outstanding PRs that depend on this? The refactors you're suggesting aren't really a part of the multithreading story.

**Comment by trptcolin** [comment]
> In any case, wouldn't testing with many more connections than cob_spec asks for and/or my tic-tac-toe game requires violate the principle "What is the simplest thing that could possibly work?"

Right, the old Agile/XP mantra. At issue for me is: what does "that could possibly work" really mean? Is it really working if it works on your machine but not a co-workers? On all developers' machines but not on the build machine? On the build machine, but not in production? On production, but not when 10 people use it? When 10 people use it, but not 1000? You see where I'm going here - yes, I agree that we don't need to spend weeks optimizing prematurely, but when we have stories about performance, it's a good idea to test the limits of the system and at least know where the bottlenecks are & what we pay in resources to get good-enough-for-now performance.

I'm mildly curious about 2 things:
1. Memory consumption - how much memory does your server use while it's running that test?
2. Latency - if you run `ab`, `siege`, or some other benchmarking tool, what's the shortest/longest/average response time? And any other stats, including percentiles/distributions/etc. are great to gather.

**Comment by trptcolin** [comment]
@hkgumbs It'd be a bummer to have untested code merged into master. This commit is pretty small, so I bet you could use `git rebase -i` on one of the other branches to re-order commits, moving this commit to the end, and then delete the commit. It'd be a good git exercise. Ultimately, if it can't be done, I can live with that, but I suspect it can - this is one of those painful cases that, if nothing else, will sharpen your git skills. :smile:

**Comment by hkgumbs** [comment]
@trptcolin gotcha. I separated out the PRs. I don't know how to test memory consumption though. Do you have any resources you could point me to that monitor that?

**Comment by hkgumbs** [comment]
This didn't seem like something that should go into an actual file:
```
➜  cob_spec git:(master) ✗ ab -n 2056 localhost:5000/
This is ApacheBench, Version 2.3 <$Revision: 1663405 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking localhost ...

Server Software:
Server Hostname:        localhost
Server Port:            5000

Document Path:          /
Document Length:        437 bytes

Concurrency Level:      1
Time taken for tests:   2.330 seconds
Complete requests:      2056
Failed requests:        0
Total transferred:      988936 bytes
HTML transferred:       898472 bytes
Requests per second:    882.56 [#/sec] (mean)
Time per request:       1.133 [ms] (mean)
Time per request:       1.133 [ms] (mean, across all concurrent requests)
Transfer rate:          414.56 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.0      0       1
Processing:     1    1   0.3      1       7
Waiting:        0    1   0.2      1       4
Total:          1    1   0.3      1       7

Percentage of the requests served within a certain time (ms)
  50%      1
  66%      1
  75%      1
  80%      1
  90%      1
  95%      2
  98%      2
  99%      2
 100%      7 (longest request)
```

**Comment by trptcolin** [comment]
A quick & dirty estimate of memory usage is looking at the processes in Activity Monitor. 

Those latencies look great! Can you also run `ab` and turn up the number of concurrent requests (via the `-c` flag)? At some point in terms of concurrency & number of requests, something falls over, so the goal here is to find out what that something is, and when it happens.

**Comment by hkgumbs** [comment]
That makes sense. I updated the post above. Should I be documenting this behavior somewhere or is it just an exercise?

I'm still not clear on how to estimate memory usage though. Activity Monitor on my server's PID just hovers around 270MB. I don't really even have a good handle on where that number should be.

**Comment by trptcolin** [comment]
Just an exercise; no need to check anything in.

270MB seems a bit high, but reasonable for a Java server process.

We'll do some more performance/reliability stuff on real projects.

**Comment by hkgumbs** [comment]
@trptcolin @robertjlooby I'll merge this this afternoon unless I hear something.

**Pull request merged**
